### ISSUE TITLE
SlimAssist -  Coordinates of the new Text Items (Discord link / InSlimVML) are not properly aligned on most resolutions

### ISSUE THREAD

**Issue by getsalty** [PJninja/InSlimVML#3]
Hello,

Currently, the new menu items that are added via SlimAssist have hard-coded x/y positions.  This means that if the display resolution is not the exact resolution of whatever this mod was designed in, it will look bad.  Here is an example:

![image](https://user-images.githubusercontent.com/836241/109175525-7d196180-774b-11eb-9dff-44e8934632b2.png)

If this project was Open Source, I would submit a PR to fix it.  But let me just say what I would do here, in hopes that it might be helpful.

I would first get the RectTransform from the Parent.
`RectTransform rt = parent as RectTransform;`

I would add a middle X point of the screen
`float screenMiddle = (Screen.width / 2);`

I would then set the "Mod Discord" position to be something like:
`obj.transform.position = new Vector3(screenMiddle, (rt.position.y - rt.rect.height) + 100f, 0f);`

I would then set the "InSlimVML v0.2.0" x and y values
`float num = screenMiddle;`
`float num2 = rt.position.y + 10f;`

Lastly I would set the "BepinEx ..." x and y values
`float num3 = screenMiddle;`
`float num4 = rt.position.y + 40f;`

Once those changes are done, the game should look like this (regardless of the display resolution)

![image](https://user-images.githubusercontent.com/836241/109176815-cd44f380-774c-11eb-82ec-14b93d0f3701.png)

**Comment by PJninja** [comment]
Thanks for that! I tossed it with matching coords but wrong alignment X.X will get to that next patch

**Comment by PJninja** [comment]
![Capture1](https://user-images.githubusercontent.com/50462051/109207887-a354f680-7777-11eb-92df-f98b80a67183.PNG)

Solved in v.0.2.2
